config/routes.rb
Rails.application.routes.draw do
  devise_for :users,:controllers=>{'registrations': 'registrations'}
  resources :tweets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


    private
    
    def sign_up_params
        params.require(:user).permit(:name,:username,:email,:password,:password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name,:username,:email,:password,:password_confirmation,:current_password)

    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!,only:[:show]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all.order("created_at DESC")
    @tweet=Tweet.new
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.build
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = current_user.tweets.build(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:tweet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar is-info">
   <div class="navbar-brand">
  		<%= link_to root_path, class: "navbar-item" do %>
  			<h1 class="title is-5">Twittter</h1>
  		<% end %>
			<div class="navbar-burger burger" data-target="navbarExample">
					<span></span>
					<span></span>
					<span></span>
  		    </div>
  	 </div>

			<div id="navbarExample" class="navbar-menu">
				<div class="navbar-end">
                    <div class="navbar-item">
                        <div class="field is-grouped">
                            <p class="control">
                                <%= link_to 'New Tweeet', new_tweet_path, class: "button is-info is-inverted" %>
                            </p>
						</div>
            		</div>
					<% if user_signed_in? %>
					<div class="navbar-item">
                        <div class="field is-grouped">
                            <p class="control">
                                <%= link_to current_user.name, edit_user_registration_path, class: "button is-info" %>
                            </p>
						</div>
            		</div>

					<div class="navbar-item">
                        <div class="field is-grouped">
                            <p class="control">
                                <%= link_to 'Log Out', destroy_user_session_path,method: :delete, class: "button is-info" %>
                            </p>
						</div>
            		</div>
					<% else %>
					<div class="navbar-item">
                        <div class="field is-grouped">
                            <p class="control">
                                <%= link_to 'Sign Up', new_user_registration_path, class: "button is-info" %>
                            </p>
						</div>
            		</div>

					<div class="navbar-item">
                        <div class="field is-grouped">
                            <p class="control">
                                <%= link_to 'Sign in', new_user_session_path, class: "button is-info" %>
                            </p>
						</div>
            		</div>
					<% end %>
					
			
				</div>
			</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/nav' %>
    <% if flash[:notice] %>
        <div class="notification is-primary global-notification">
          <p class="notice">
            <%= notice %>
          </p>
        </div>      
    <% end %>

        <% if flash[:alert] %>
        <div class="notification is-danger global-alert">
          <p class="alert">
            <%= alert %>
          </p>
        </div>      
    <% end %>
  
    <%= yield %>
  </body>
</html>

app/views/tweets/_feed.html.erb
<div class="column is-half">
<% if user_signed_in? %>
    <article class="media box">
        <figure class="media-left">
            <p class="image is-64x64">
				<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>

            </p>
        </figure>

        <div class="media-content">
            <%= render 'tweets/form' %>
        </div>
    </article>
    <% end %>

<% @tweets.each  do |tweet|%>
<div class="box">
    <article class="media">
        <figure class="media-left">
            <p class="image is-64x64">
				<%= gravatar_image_tag(tweet.user.email, size: 64, alt: tweet.user.name) %>

            </p>
        </figure>

        <div class="media-content">
            <div class="content">
                <strong><%= tweet.user.name %></strong>
                <small>@<%= tweet.user.username%></small>
                <p>
                    <%= tweet.tweet %>
                </p>
            </div>
            <% if user_signed_in? %>
            <nav class="level">
                <div class="level-left is-mobile">
                    <%= link_to tweet, class:"level-item" do %>
                        <span class="icon">
                            <i class="fa fa-link" aria-hidden="true">

                            </i>
                        </span>
                    <% end %> 

                     <%= link_to edit_tweet_path(tweet), class:"level-item" do %>
                        <span class="icon">
                         <span class="fa fa-italic" aria-hidden="true"></span>
                        </span>
                    <% end %>   
                     <%= link_to tweet_path(tweet), class:"level-item" ,method: :delete ,data:{confirm: "are you sure ?"} do %>
                        <span class="icon">
                         <i class="fa fa-trash"></i>
                        </span>
                    <% end %>                  
                </div>
            </nav>
            <% end %>
        </div>
    </article>
</div>
<% end %>
</div>

app/views/tweets/_form.html.erb
<%= simple_form_for(@tweet) do |f| %>
  <%= f.error_notification %>
  <div class="field">
    <div class="control">
    <%= f.input :tweet, label: "Tweeet about it", input_html: { class: "textarea "}, wrapper: false, label_html: {class: "label"}, placeholder: "Compose a new tweeet...", autofocus: true %>    </div>
  </div>
  <%= f.button :submit ,class:"button is-primary"%>

<% end %>

app/views/tweets/_profile.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Profile</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-left">
					<figure class="image is-64x64">
						<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
					</figure>
				</div>
				<div class="media-content">
					<div class="content">
						<p>
							<strong><%= current_user.name %></strong><br />
							<small><%= current_user.username %></small>
						</p>
					</div>
				</div>
			</article>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Tweets</p>
						<p class="title is-6"><%= current_user.tweets.count %></p>
					</div>
				</div>
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Following</p>
						<p class="title is-6">123</p>
					</div>
				</div>
					<div class="level-item has-centered-text">
					<div>
						<p class="heading">Followers</p>
						<p class="title is-6">465K</p>
					</div>
				</div>
			</div>
		</div>
	</nav>
</div>

app/views/tweets/_trends.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Trends</p>
		<a class="panel-block">
			Trend 1
		</a>
		<a class="panel-block">
			Trend 2
		</a>
		<a class="panel-block">
			Trend 3
		</a>
		<a class="panel-block">
			Trend 4
		</a>
		<a class="panel-block">
			Trend 5
		</a>
		<a class="panel-block">
			Trend 6
		</a>
	</nav>
</div>

app/views/tweets/_who_to_follow.html.erb
<div class="column">
	<nav class="panel">
		<p class="panel-heading">Who to Follow</p>
	
	<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong>John Smith</strong>
						<small>@johnsmith</small>
					</p>
				</div>
			</div>
		</article>
	</div>
		<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong>John Smith</strong>
						<small>@johnsmith</small>
					</p>
				</div>
			</div>
		</article>
	</div>
		<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong>John Smith</strong>
						<small>@johnsmith</small>
					</p>
				</div>
			</div>
		</article>
	</div>
	</nav>
</div>

app/views/tweets/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Tweet</h1>
				<%= render 'form', tweeet: @tweet %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', tweets_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/tweets/index.html.erb
<div class="section">
  <div class="container">
    <div class="columns">
      <% if user_signed_in? %>
        <%= render 'profile' %>
      <% else %>
        <%= render 'trends' %>
      <% end %>
        
        <%= render 'feed' %>
        <%= render 'who_to_follow' %>
    </div>
  </div>
</div>

app/views/tweets/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Create a new Tweet</h1>
					<%= render 'form', tweeet: @tweet %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', tweets_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/tweets/show.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<p>
          <strong>Tweet:</strong>
          <%= @tweet.tweet %>
        </p>
        <nav class="navbar is-fixed-bottom">
            <div class="navbar-menu">
              <div class="navbar-item">
                <div class="field is-grouped">
                  <p class="control">
                  <%= link_to 'Edit', edit_tweet_path(@tweet) ,class:"button is-primary"%> 
                  </p>
              </div>
              <div class="navbar-item">
                <div class="field is-grouped">
                  <p class="control">
                  <%= link_to 'Back', tweets_path ,class:"button is-info"%>
                  </p>
              </div>
            </div>
             </nav>
			</div>
		</div>
	</div>
</div>